---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-backend-service
spec:
  type: ClusterIP
  selector:
    app: url-shortener-backend
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: url-shortener-frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-backend
  labels:
    app: url-shortener-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener-backend
  template:
    metadata:
      labels:
        app: url-shortener-backend
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/url-shortener/backend:IMAGE_TAG
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          value: "DB_USER_VALUE"
        - name: PASSWORD
          value: "PASSWORD_VALUE"
        - name: HOST
          value: "HOST_VALUE"
        - name: PORT
          value: "PORT_VALUE"
        - name: DATABASE
          value: "DATABASE_VALUE"
        - name: DATABASE_URL
          value: "DATABASE_URL_VALUE"
        - name: DEBUG
          value: "DEBUG_VALUE"
        - name: BASE_URL
          value: "BASE_URL_VALUE"
        - name: BASE_URL_FRONTEND
          value: "BASE_URL_FRONTEND_VALUE"
        - name: SUPABASE_URL
          value: "SUPABASE_URL_VALUE"
        - name: SUPABASE_ANON_KEY
          value: "SUPABASE_ANON_KEY_VALUE"
        - name: SUPABASE_SERVICE_ROLE_KEY
          value: "SUPABASE_SERVICE_ROLE_KEY_VALUE"
        - name: JWT_SECRET
          value: "JWT_SECRET_VALUE"
        - name: JWT_EXPIRY
          value: "JWT_EXPIRY_VALUE"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-frontend
  labels:
    app: url-shortener-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener-frontend
  template:
    metadata:
      labels:
        app: url-shortener-frontend
    spec:
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/url-shortener/frontend:IMAGE_TAG
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
